spanish translation
LLEB-ME/wiki pull request #23
Opened 2022-09-04 06:19 UTC by risih

2022-09-04 06:24 UTC, doamatto commented
Needs proper formatting for HTML.

2022-09-04 06:24 UTC, doamatto requested changes
Needs proper formatting for HTML.

2022-09-21 03:51 UTC, cyckl commented
Decided to remove Spanish and the `ri` dialect in #24.

2022-09-21 03:51 UTC, closed without merging

2022-09-21 04:00 UTC, cyckl reviewed
marking this so it gets out of my inbox